### ISSUE TITLE
dm doesn't work at all

### ISSUE THREAD

**Issue by insyri** [rsource-open-source/rsource-records#3]
simply doesnt return a message object on dm.

**Comment by insyri** [comment]
this is a discordjs bug, likely resolved in the detritus switch

**Comment by dowoge** [comment]
u suck
( i love you )

**Comment by insyri** [comment]
ily2 doge :3

**Comment by dowoge** [comment]
😆♥♥♥♥♥💘♥♥❤❤❤❤❤🤎😍😍💖
