### ISSUE TITLE
FIGURE OUT WHAT THE FUCK IS WRONG WITH FETCHING

### ISSUE THREAD

**Issue by insyri** [rsource-open-source/rsource-records#35]

**Comment by insyri** [comment]
once done the curl stuff will be unneeded and easy to rewrite anyways, so why not do it now?

**Comment by insyri** [comment]
its funny cuz when i tried literally everything @arcy-at just comes in and fixes it like he knew whats up :D
kill me

**Comment by insyri** [comment]
@arcy-at CHANGE YOUR RSOURCE ORG FROM `rsource` TO `rsource-open-source`
thxxx

**Comment by trueharuu** [comment]
🇳🇪

**Comment by insyri** [comment]
for future reference, the problem was solved by using an older version of node-fetch, of do I know why? no, no I don't, and as long as it works, I won't question it.

**Comment by trueharuu** [comment]
newer versions of node-fetch use esm modules instead of CommonJS ones, thus making you use esm modules for the entire project (node gods please fix), which breaks all the commonJS imports (meaning that you have to use one or the other, never a mix)

**Comment by jaydns** [comment]
well they cant fix it cause they did it on purpose, cause tbh commonjs modules are nasty

rsource records should switch maybe if detritus supports them

**Comment by insyri** [comment]
why did they even change the modules types n shit, just makes the whole thing complicated bit alrite (half rhetorical)

i'll see the science of modules and shit soon to see what I could do to improve

**Comment by jaydns** [comment]
node-fetch changed it cause its the more modern way to do things, commonjs isnt actually part of the js standard but esmodules are and i think esmodules are faster, the syntax is also simpler than require/module.exports

**Comment by insyri** [comment]
ah i see, that makes a little more sense

putting this here for future research
https://www.typescriptlang.org/docs/handbook/2/modules.html
